; ZAX lowered ASM80 output

ORG $0100
; ZAX: func inc_one begin
inc_one:
push ix
ld ix, $00
add ix, sp
ld hl, $22
push hl
ld hl, $33
push hl
push af
push bc
push de
ld e, (IX+$04)
ld d, (IX+$05)
inc de
ld (IX-$02), e
ld (IX-$01), d
ld e, (IX-$02)
ld d, (IX-$01)
ex de, hl
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func inc_one end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push hl
ld hl, $11
ex (SP), hl
push af
push bc
push de
push hl
ld hl, $44
push hl
DB $CD, $00, $00
inc sp
inc sp
ex de, hl
ld (IX-$02), e
ld (IX-$01), d
ex de, hl
__zax_epilogue_1:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end
