; ZAX lowered ASM80 output

ORG $1000
bytes10:
DB $01
DB $02
DB $03
DB $04
DB $05
DB $06
DB $07
DB $08
DB $09
DB $0A
words4:
DW $64
DW $C8
DW $012C
DW $0190

ORG $0100
; ZAX: func first_byte begin
first_byte:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
DB $3A, $00, $00
ld l, a
ld h, $00
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func first_byte end
; ZAX: func read_word_at begin
read_word_at:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push de
DB $11, $00, $00
ex de, hl
ld e, (IX+$04)
ld d, (IX+$05)
ex de, hl
add hl, hl
add hl, de
ld e, (HL)
inc hl
ld d, (HL)
ld l, e
ld h, d
pop de
__zax_epilogue_1:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func read_word_at end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push hl
ld hl, $02
ex (SP), hl
push af
push bc
push de
push hl
DB $CD, $00, $00
ex de, hl
ld e, (IX-$02)
ld d, (IX-$01)
ex de, hl
push hl
DB $CD, $00, $00
inc sp
inc sp
__zax_epilogue_2:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $1012
__zax_startup:
DB $21, $5A, $10, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $6A, $10, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $40, $01
DB $02, $00, $00, $10, $00, $00, $0A, $00, $0A, $10, $0A, $00, $08, $00, $00, $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0A, $64, $00, $C8, $00, $2C, $01, $90, $01
