; ZAX lowered ASM80 output

ORG $1000
pair_buf:
DB $00
DB $00

ORG $0100
; ZAX: func write_pair begin
write_pair:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
push af
DB $DD, $7E, $04
DB $32, $00, $00
pop af
push af
DB $DD, $7E, $06
DB $32, $00, $00
pop af
__zax_epilogue_0:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func write_pair end
; ZAX: func read_pair_word begin
read_pair_word:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push af
DB $3A, $00, $00
ld l, a
pop af
push af
DB $3A, $00, $00
ld h, a
pop af
__zax_epilogue_1:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func read_pair_word end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
ld hl, $02
push hl
ld hl, $01
push hl
DB $CD, $00, $00
inc sp
inc sp
inc sp
inc sp
DB $3A, $00, $00
DB $CD, $00, $00
__zax_epilogue_2:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $1002
__zax_startup:
DB $21, $4A, $10, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $54, $10, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $44, $01
DB $01, $00, $00, $10, $00, $00, $02, $00, $00, $00, $00, $00
