; ZAX lowered ASM80 output

ORG $1000
sample_byte:
DB $07
sample_word:
DW $64

ORG $0100
; ZAX: func add_to_sample begin
add_to_sample:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
DB $2A, $00, $00
ld e, (IX+$04)
ld d, (IX+$05)
xor a
adc hl, de
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func add_to_sample end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push hl
ld hl, $00
ex (SP), hl
push af
push bc
push de
push hl
DB $3A, $00, $00
ld hl, $17
push hl
DB $CD, $00, $00
inc sp
inc sp
ex de, hl
ld (IX-$02), e
ld (IX-$01), d
ex de, hl
__zax_epilogue_1:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $1003
__zax_startup:
DB $21, $4B, $10, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $5B, $10, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $1F, $01
DB $02, $00, $00, $10, $00, $00, $01, $00, $01, $10, $01, $00, $02, $00, $00, $00, $07, $64, $00
