; ZAX lowered ASM80 output

ORG $2000
glob_words:
DW $1001
DW $1002
DW $1003
DW $1004
DW $1005
DW $1006
DW $1007
DW $1008

ORG $0100
; ZAX: func word_glob_const begin
word_glob_const:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push de
DB $ED, $5B, $00, $00
push hl
push de
DB $11, $00, $00
ld hl, $02
add hl, hl
add hl, de
pop de
ld (HL), e
inc hl
ld (HL), d
pop hl
pop de
DB $2A, $00, $00
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func word_glob_const end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
DB $CD, $00, $00
__zax_epilogue_1:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $2010
__zax_startup:
DB $21, $58, $20, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $62, $20, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $2B, $01
DB $01, $00, $00, $20, $00, $00, $10, $00, $00, $00, $01, $10, $02, $10, $03, $10, $04, $10, $05, $10, $06, $10, $07, $10, $08, $10
